on:
  push:
    branches:
    - main
  pull_request:

# Keeping this file separate as the dependencies check would use more
# repositories than needed this downstream check for GraalVM native image and
# other Maven plugins.
name: downstream
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21]
        repo:
        - java-bigquery
        - java-bigtable
        - java-storage
        - java-storage-nio
        - java-spanner
        - java-spanner-jdbc
        - java-pubsub
        - java-pubsublite
        - java-logging
        - java-logging-logback
        - java-firestore
        - java-datastore
        - java-bigquerystorage
        job-type:
        - test  # maven-surefire-plugin
        - lint  # fmt-maven-plugin and google-java-format
        - clirr # clirr-maven-plugin
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get update -y
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/client-library-check.sh ${{matrix.repo}} ${{matrix.job-type}}
  javadoc-with-doclet:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17] # Run only on Java 17 as that's what c.g.c. generation uses
        repo:
        - java-bigtable
        - java-bigquery
        - java-storage
        - java-storage-nio
        - java-spanner
        - java-spanner-jdbc
        - java-pubsub
        - java-pubsublite
        - java-logging
        - java-logging-logback
        - java-firestore
        - java-datastore
        - java-bigquerystorage
        job-type:
        - javadoc-with-doclet # test c.g.c. - specific documentation generation
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get update -y
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/client-library-check-doclet.sh ${{matrix.repo}}
